version: '2.2'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f bundle.zip ]]; then
          /usr/share/elasticsearch/bin/elasticsearch-certutil cert --silent --pem --in /usr/share/elasticsearch/config/certificates/instances.yml -out /usr/share/elasticsearch/config/certificates/bundle.zip;
          unzip bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
#    working_dir: /usr/share/elasticsearch/config/certificates
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certificates
    working_dir: /usr/share/elasticsearch/config/certificates
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
